server:
  port: 8040

#应用名称 (nacos会将该服务当成服务名称)
spring:
  application:
    name: order-service
  cloud:
    nacos:
      server-addr: 192.168.204.1:8848
      discovery:
        username: nacos
        password: nacos
        namespace: public
nobody:
  json:
    suffix-name: "@"
    prefix-name: "&"

# springboot 默认的日志基本是 info ,feign的日志级别就不会
logging:
  level:
    com:
      leran:
        order:
          fegin: debug
feign:
  client:
    config:
      product-service:
        loggerLevel: BASIC
        #contract: feign.Contract.Default #设置默认的契约
        connectTimeout: 5000
        redTimeout: 10000
        requestInterceptors[0]:
          com.leran.order.inertcptor.feign.CustomFeignInterceptor