
spring:
  profiles:
    active: dev

#在配置中心可以通过  profile进行设置
#只有默认的配置文件 和服务名相同的配置文件 就是 默认配置文件
#对应的 dataId: ${spring.application.name}-${profile}.${file-extension:properties}
server:
  port: 8800

# springboot 默认的日志基本是 info ,feign的日志级别就不会
logging:
  level:
    com:
      leran:
        order:
          fegin: debug
feign:
  client:
    config:
      demo-service:
        loggerLevel: BASIC
        #contract: feign.Contract.Default #设置默认的契约
        connectTimeout: 5000
        redTimeout: 10000
        requestInterceptors[0]:
          com.leran.demo.inertcptor.feign.CustomFeignInterceptor
