server:
  port: 8020

#应用名称 (nacos会将该服务当成服务名称)
spring:
  application:
    name: order-service
  cloud:
    nacos:
      server-addr: 192.168.204.1:8848
      discovery:
        username: nacos
        password: nacos
        namespace: public